/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.young.thrift.module;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-11-29")
public class UserInfo implements org.apache.thrift.TBase<UserInfo, UserInfo._Fields>, java.io.Serializable, Cloneable, Comparable<UserInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserInfo");

  private static final org.apache.thrift.protocol.TField TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("token", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField IMEI_FIELD_DESC = new org.apache.thrift.protocol.TField("imei", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PT_FIELD_DESC = new org.apache.thrift.protocol.TField("pt", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DT_FIELD_DESC = new org.apache.thrift.protocol.TField("dt", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CID_FIELD_DESC = new org.apache.thrift.protocol.TField("cid", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CH_FIELD_DESC = new org.apache.thrift.protocol.TField("ch", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField TM_FIELD_DESC = new org.apache.thrift.protocol.TField("tm", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField PM_FIELD_DESC = new org.apache.thrift.protocol.TField("pm", org.apache.thrift.protocol.TType.I32, (short)8);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserInfoTupleSchemeFactory();

  public int token; // required
  public String imei; // required
  public String pt; // required
  public String dt; // required
  public String cid; // required
  public String ch; // required
  public int tm; // required
  public int pm; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TOKEN((short)1, "token"),
    IMEI((short)2, "imei"),
    PT((short)3, "pt"),
    DT((short)4, "dt"),
    CID((short)5, "cid"),
    CH((short)6, "ch"),
    TM((short)7, "tm"),
    PM((short)8, "pm");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TOKEN
          return TOKEN;
        case 2: // IMEI
          return IMEI;
        case 3: // PT
          return PT;
        case 4: // DT
          return DT;
        case 5: // CID
          return CID;
        case 6: // CH
          return CH;
        case 7: // TM
          return TM;
        case 8: // PM
          return PM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOKEN_ISSET_ID = 0;
  private static final int __TM_ISSET_ID = 1;
  private static final int __PM_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TOKEN, new org.apache.thrift.meta_data.FieldMetaData("token", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IMEI, new org.apache.thrift.meta_data.FieldMetaData("imei", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PT, new org.apache.thrift.meta_data.FieldMetaData("pt", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DT, new org.apache.thrift.meta_data.FieldMetaData("dt", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CID, new org.apache.thrift.meta_data.FieldMetaData("cid", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CH, new org.apache.thrift.meta_data.FieldMetaData("ch", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TM, new org.apache.thrift.meta_data.FieldMetaData("tm", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PM, new org.apache.thrift.meta_data.FieldMetaData("pm", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserInfo.class, metaDataMap);
  }

  public UserInfo() {
  }

  public UserInfo(
    int token,
    String imei,
    String pt,
    String dt,
    String cid,
    String ch,
    int tm,
    int pm)
  {
    this();
    this.token = token;
    setTokenIsSet(true);
    this.imei = imei;
    this.pt = pt;
    this.dt = dt;
    this.cid = cid;
    this.ch = ch;
    this.tm = tm;
    setTmIsSet(true);
    this.pm = pm;
    setPmIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserInfo(UserInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.token = other.token;
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetPt()) {
      this.pt = other.pt;
    }
    if (other.isSetDt()) {
      this.dt = other.dt;
    }
    if (other.isSetCid()) {
      this.cid = other.cid;
    }
    if (other.isSetCh()) {
      this.ch = other.ch;
    }
    this.tm = other.tm;
    this.pm = other.pm;
  }

  public UserInfo deepCopy() {
    return new UserInfo(this);
  }

  @Override
  public void clear() {
    setTokenIsSet(false);
    this.token = 0;
    this.imei = null;
    this.pt = null;
    this.dt = null;
    this.cid = null;
    this.ch = null;
    setTmIsSet(false);
    this.tm = 0;
    setPmIsSet(false);
    this.pm = 0;
  }

  public int getToken() {
    return this.token;
  }

  public UserInfo setToken(int token) {
    this.token = token;
    setTokenIsSet(true);
    return this;
  }

  public void unsetToken() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOKEN_ISSET_ID);
  }

  /** Returns true if field token is set (has been assigned a value) and false otherwise */
  public boolean isSetToken() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOKEN_ISSET_ID);
  }

  public void setTokenIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOKEN_ISSET_ID, value);
  }

  public String getImei() {
    return this.imei;
  }

  public UserInfo setImei(String imei) {
    this.imei = imei;
    return this;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getPt() {
    return this.pt;
  }

  public UserInfo setPt(String pt) {
    this.pt = pt;
    return this;
  }

  public void unsetPt() {
    this.pt = null;
  }

  /** Returns true if field pt is set (has been assigned a value) and false otherwise */
  public boolean isSetPt() {
    return this.pt != null;
  }

  public void setPtIsSet(boolean value) {
    if (!value) {
      this.pt = null;
    }
  }

  public String getDt() {
    return this.dt;
  }

  public UserInfo setDt(String dt) {
    this.dt = dt;
    return this;
  }

  public void unsetDt() {
    this.dt = null;
  }

  /** Returns true if field dt is set (has been assigned a value) and false otherwise */
  public boolean isSetDt() {
    return this.dt != null;
  }

  public void setDtIsSet(boolean value) {
    if (!value) {
      this.dt = null;
    }
  }

  public String getCid() {
    return this.cid;
  }

  public UserInfo setCid(String cid) {
    this.cid = cid;
    return this;
  }

  public void unsetCid() {
    this.cid = null;
  }

  /** Returns true if field cid is set (has been assigned a value) and false otherwise */
  public boolean isSetCid() {
    return this.cid != null;
  }

  public void setCidIsSet(boolean value) {
    if (!value) {
      this.cid = null;
    }
  }

  public String getCh() {
    return this.ch;
  }

  public UserInfo setCh(String ch) {
    this.ch = ch;
    return this;
  }

  public void unsetCh() {
    this.ch = null;
  }

  /** Returns true if field ch is set (has been assigned a value) and false otherwise */
  public boolean isSetCh() {
    return this.ch != null;
  }

  public void setChIsSet(boolean value) {
    if (!value) {
      this.ch = null;
    }
  }

  public int getTm() {
    return this.tm;
  }

  public UserInfo setTm(int tm) {
    this.tm = tm;
    setTmIsSet(true);
    return this;
  }

  public void unsetTm() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TM_ISSET_ID);
  }

  /** Returns true if field tm is set (has been assigned a value) and false otherwise */
  public boolean isSetTm() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TM_ISSET_ID);
  }

  public void setTmIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TM_ISSET_ID, value);
  }

  public int getPm() {
    return this.pm;
  }

  public UserInfo setPm(int pm) {
    this.pm = pm;
    setPmIsSet(true);
    return this;
  }

  public void unsetPm() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PM_ISSET_ID);
  }

  /** Returns true if field pm is set (has been assigned a value) and false otherwise */
  public boolean isSetPm() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PM_ISSET_ID);
  }

  public void setPmIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PM_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TOKEN:
      if (value == null) {
        unsetToken();
      } else {
        setToken((Integer)value);
      }
      break;

    case IMEI:
      if (value == null) {
        unsetImei();
      } else {
        setImei((String)value);
      }
      break;

    case PT:
      if (value == null) {
        unsetPt();
      } else {
        setPt((String)value);
      }
      break;

    case DT:
      if (value == null) {
        unsetDt();
      } else {
        setDt((String)value);
      }
      break;

    case CID:
      if (value == null) {
        unsetCid();
      } else {
        setCid((String)value);
      }
      break;

    case CH:
      if (value == null) {
        unsetCh();
      } else {
        setCh((String)value);
      }
      break;

    case TM:
      if (value == null) {
        unsetTm();
      } else {
        setTm((Integer)value);
      }
      break;

    case PM:
      if (value == null) {
        unsetPm();
      } else {
        setPm((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TOKEN:
      return getToken();

    case IMEI:
      return getImei();

    case PT:
      return getPt();

    case DT:
      return getDt();

    case CID:
      return getCid();

    case CH:
      return getCh();

    case TM:
      return getTm();

    case PM:
      return getPm();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TOKEN:
      return isSetToken();
    case IMEI:
      return isSetImei();
    case PT:
      return isSetPt();
    case DT:
      return isSetDt();
    case CID:
      return isSetCid();
    case CH:
      return isSetCh();
    case TM:
      return isSetTm();
    case PM:
      return isSetPm();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UserInfo)
      return this.equals((UserInfo)that);
    return false;
  }

  public boolean equals(UserInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_token = true;
    boolean that_present_token = true;
    if (this_present_token || that_present_token) {
      if (!(this_present_token && that_present_token))
        return false;
      if (this.token != that.token)
        return false;
    }

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_pt = true && this.isSetPt();
    boolean that_present_pt = true && that.isSetPt();
    if (this_present_pt || that_present_pt) {
      if (!(this_present_pt && that_present_pt))
        return false;
      if (!this.pt.equals(that.pt))
        return false;
    }

    boolean this_present_dt = true && this.isSetDt();
    boolean that_present_dt = true && that.isSetDt();
    if (this_present_dt || that_present_dt) {
      if (!(this_present_dt && that_present_dt))
        return false;
      if (!this.dt.equals(that.dt))
        return false;
    }

    boolean this_present_cid = true && this.isSetCid();
    boolean that_present_cid = true && that.isSetCid();
    if (this_present_cid || that_present_cid) {
      if (!(this_present_cid && that_present_cid))
        return false;
      if (!this.cid.equals(that.cid))
        return false;
    }

    boolean this_present_ch = true && this.isSetCh();
    boolean that_present_ch = true && that.isSetCh();
    if (this_present_ch || that_present_ch) {
      if (!(this_present_ch && that_present_ch))
        return false;
      if (!this.ch.equals(that.ch))
        return false;
    }

    boolean this_present_tm = true;
    boolean that_present_tm = true;
    if (this_present_tm || that_present_tm) {
      if (!(this_present_tm && that_present_tm))
        return false;
      if (this.tm != that.tm)
        return false;
    }

    boolean this_present_pm = true;
    boolean that_present_pm = true;
    if (this_present_pm || that_present_pm) {
      if (!(this_present_pm && that_present_pm))
        return false;
      if (this.pm != that.pm)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + token;

    hashCode = hashCode * 8191 + ((isSetImei()) ? 131071 : 524287);
    if (isSetImei())
      hashCode = hashCode * 8191 + imei.hashCode();

    hashCode = hashCode * 8191 + ((isSetPt()) ? 131071 : 524287);
    if (isSetPt())
      hashCode = hashCode * 8191 + pt.hashCode();

    hashCode = hashCode * 8191 + ((isSetDt()) ? 131071 : 524287);
    if (isSetDt())
      hashCode = hashCode * 8191 + dt.hashCode();

    hashCode = hashCode * 8191 + ((isSetCid()) ? 131071 : 524287);
    if (isSetCid())
      hashCode = hashCode * 8191 + cid.hashCode();

    hashCode = hashCode * 8191 + ((isSetCh()) ? 131071 : 524287);
    if (isSetCh())
      hashCode = hashCode * 8191 + ch.hashCode();

    hashCode = hashCode * 8191 + tm;

    hashCode = hashCode * 8191 + pm;

    return hashCode;
  }

  @Override
  public int compareTo(UserInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetToken()).compareTo(other.isSetToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.token, other.token);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImei()).compareTo(other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPt()).compareTo(other.isSetPt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pt, other.pt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDt()).compareTo(other.isSetDt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dt, other.dt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCid()).compareTo(other.isSetCid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cid, other.cid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCh()).compareTo(other.isSetCh());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCh()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ch, other.ch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTm()).compareTo(other.isSetTm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tm, other.tm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPm()).compareTo(other.isSetPm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pm, other.pm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UserInfo(");
    boolean first = true;

    sb.append("token:");
    sb.append(this.token);
    first = false;
    if (!first) sb.append(", ");
    sb.append("imei:");
    if (this.imei == null) {
      sb.append("null");
    } else {
      sb.append(this.imei);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pt:");
    if (this.pt == null) {
      sb.append("null");
    } else {
      sb.append(this.pt);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dt:");
    if (this.dt == null) {
      sb.append("null");
    } else {
      sb.append(this.dt);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cid:");
    if (this.cid == null) {
      sb.append("null");
    } else {
      sb.append(this.cid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ch:");
    if (this.ch == null) {
      sb.append("null");
    } else {
      sb.append(this.ch);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tm:");
    sb.append(this.tm);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pm:");
    sb.append(this.pm);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'token' because it's a primitive and you chose the non-beans generator.
    if (imei == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'imei' was not present! Struct: " + toString());
    }
    if (pt == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'pt' was not present! Struct: " + toString());
    }
    if (dt == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dt' was not present! Struct: " + toString());
    }
    if (cid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'cid' was not present! Struct: " + toString());
    }
    if (ch == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ch' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'tm' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'pm' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserInfoStandardScheme getScheme() {
      return new UserInfoStandardScheme();
    }
  }

  private static class UserInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<UserInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.token = iprot.readI32();
              struct.setTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IMEI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.imei = iprot.readString();
              struct.setImeiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pt = iprot.readString();
              struct.setPtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dt = iprot.readString();
              struct.setDtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cid = iprot.readString();
              struct.setCidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ch = iprot.readString();
              struct.setChIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tm = iprot.readI32();
              struct.setTmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pm = iprot.readI32();
              struct.setPmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetToken()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'token' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTm()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'tm' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPm()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pm' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TOKEN_FIELD_DESC);
      oprot.writeI32(struct.token);
      oprot.writeFieldEnd();
      if (struct.imei != null) {
        oprot.writeFieldBegin(IMEI_FIELD_DESC);
        oprot.writeString(struct.imei);
        oprot.writeFieldEnd();
      }
      if (struct.pt != null) {
        oprot.writeFieldBegin(PT_FIELD_DESC);
        oprot.writeString(struct.pt);
        oprot.writeFieldEnd();
      }
      if (struct.dt != null) {
        oprot.writeFieldBegin(DT_FIELD_DESC);
        oprot.writeString(struct.dt);
        oprot.writeFieldEnd();
      }
      if (struct.cid != null) {
        oprot.writeFieldBegin(CID_FIELD_DESC);
        oprot.writeString(struct.cid);
        oprot.writeFieldEnd();
      }
      if (struct.ch != null) {
        oprot.writeFieldBegin(CH_FIELD_DESC);
        oprot.writeString(struct.ch);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TM_FIELD_DESC);
      oprot.writeI32(struct.tm);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PM_FIELD_DESC);
      oprot.writeI32(struct.pm);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserInfoTupleScheme getScheme() {
      return new UserInfoTupleScheme();
    }
  }

  private static class UserInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<UserInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.token);
      oprot.writeString(struct.imei);
      oprot.writeString(struct.pt);
      oprot.writeString(struct.dt);
      oprot.writeString(struct.cid);
      oprot.writeString(struct.ch);
      oprot.writeI32(struct.tm);
      oprot.writeI32(struct.pm);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.token = iprot.readI32();
      struct.setTokenIsSet(true);
      struct.imei = iprot.readString();
      struct.setImeiIsSet(true);
      struct.pt = iprot.readString();
      struct.setPtIsSet(true);
      struct.dt = iprot.readString();
      struct.setDtIsSet(true);
      struct.cid = iprot.readString();
      struct.setCidIsSet(true);
      struct.ch = iprot.readString();
      struct.setChIsSet(true);
      struct.tm = iprot.readI32();
      struct.setTmIsSet(true);
      struct.pm = iprot.readI32();
      struct.setPmIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

